---
- hosts: localhost
  tasks: 
    - ec2:
        key_name: bastion_host
        instance_type: t2.micro
        region: us-east-1
        image: ami-0323c3dd2da7fb37d
        count: 1
        instance_tags:
            name: created_by_ansible
            