---
- hosts: localhost
  tasks:
    - name: example using security group rule descriptions
      ec2_group:
        name: allow_80
        description: sg with rule descriptions
        region: us-east-1
        #state: absent
        rules:
            - proto: tcp
            ports:
            - 80
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on port 80
